// export const DEF_RISEACT_ACCOUNTS_URL = "https://accounts.riseact.org";
// export const DEF_RISEACT_CORE_URL = "https://core.riseact.org";
export const DEF_RISEACT_ACCOUNTS_URL = 'http://accounts.localhost:8000';
export const DEF_RISEACT_CORE_URL = 'http://core.localhost:8000';
export const COOKIE_CODE_VERIFIER = 'X-Riseact-Code-Verifier';
export const COOKIE_REFRESH_TOKEN = 'X-Riseact-Refresh-Token';
export const DEF_SQLITE_PATH = 'credentials.db';
export const TOKEN_COOKIE_NAME = 'client-token';
export const DEF_APP_HOST = 'http://localhost:3000';